config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    sessions:'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :products
    resources :orders do
        member do
          post :cancel
          post :ship
          post :shipped
          post :return
        end
      end
  end

  namespace :account do
    resources :orders
  end


  resources :products do
    member do
      get :funding_product
      post :add_to_cart
      post :add_to_cart_f
    end
    collection do
       get :search
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders  do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end


  # root 'welcome#index'
  root 'products#index'

  get '/health' => 'activity#health'
  get 'funding' => 'products#funding'
  # get 'funding_product' => 'products#funding_product'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0

    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        if cart_item.product.id==2 || cart_item.product.id==4
          if cart_item.product.fund_price1==0
            sum += cart_item.quantity * cart_item.product.fund_price2
          elsif cart_item.product.fund_price2==0
            sum += cart_item.quantity * cart_item.product.fund_price1
          end
        else
          sum += cart_item.quantity * cart_item.product.price
        end
      end
    end


    sum
  end

  def clean!
    cart_items.destroy_all
  end

end

app/views/carts/checkout.html.erb
<body id="labtop">
  <div class="container-fluid">
    <%= render "common/navbar" %>
        <%= render "common/flashes" %>
    <div id="main">
        <section id="mainCampaign">
            <div class="wrap">
                <section id="newItem">
                    <div class="content">
                        <div class="row">
                            <div class="col-md-12">

                                <h2>
                                    购物明细
                                </h2>

                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th width="80%">商品明细</th>
                                            <th>单价</th>
                                            <th>数量</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        <% current_cart.cart_items.each do |cart_item| %>
                                        <tr>
                                            <td>
                                                <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
                                            </td>
                                            <%if cart_item.product.id==2 || cart_item.product.id==4%>
                                              <%if cart_item.product.fund_price1==0%>
                                                <td>
                                                    <%= cart_item.product.fund_price2 %>
                                                </td>
                                              <%elsif cart_item.product.fund_price2==0%>
                                                <td>
                                                    <%= cart_item.product.fund_price1 %>
                                                </td>
                                              <%end%>
                                            <%else%>
                                            <td>
                                                <%= cart_item.product.price %>
                                            </td>
                                            <%end%>
                                            <td>
                                                <%= cart_item.quantity %>
                                            </td>

                                        </tr>
                                        <% end %>

                                    </tbody>
                                </table>

                                <div class="total clearfix">
                                    <span class="pull-right">
                                        总计
                                        <%= render_cart_total_price(current_cart) %>
                                        CNY
                                    </span>
                                </div>

                                <hr>

                                <h2>
                                    订单资讯
                                </h2>

                                <div class="order-form">

                                    <%= simple_form_for @order do |f| %>

                                    <legend>
                                        订购人</legend>
                                    <div class="form-group col-lg-6">
                                        <%= f.input :billing_name  %>
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <%= f.input :billing_address  %>
                                    </div>

                                    <legend>
                                        收货人</legend>
                                    <div class="form-group col-lg-6">
                                        <%= f.input :shipping_name  %>
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <%= f.input :shipping_address  %>
                                    </div>

                                    <div class="checkout">
                                        <%= f.submit "生成订单", class: "btn btn-lg btn-danger pull-right",
                       data: { disable_with: "Submitting..." } %>
                                    </div>
                                    <% end %>

                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </section>
    </div>
  </div>
</body>

app/views/carts/index.html.erb
<!DOCTYPE html>

<html lang="zh-cn" xml:lang="zh-cn" xmlns="http://www.w3.org/1999/xhtml">
    <head>

        <meta name="Description" content="">
        <meta name="Keywords" content="">
        <meta charset="utf-8">

        <title>

            购物车 | 防霾库
        </title>

        <link rel="contents" href="/" title="Home">

        <!-- 追加 -->
        <link href="//www.muji.com.cn/cn/store/css/muji.css" rel="stylesheet" type="text/css">
        <!--[if lt IE 9]><script src="//www.muji.com.cn/cn/store/js/html5.js"></script><![endif]-->

    </head>
    <body id="labtop">
      <div class="container-fluid">
        <%= render "common/navbar" %>
            <%= render "common/flashes" %>
        <script type="text/javascript">
            function showBag(flg) {
                if (flg == "1") {
                    document.getElementById("gnav_cart_target").style.display = 'block';
                } else {
                    document.getElementById("gnav_cart_target").style.display = 'none';
                }

            }
        </script>


    <div class="content">

        <div id="main" class="centerContent">


            <h2>
                 购物车
            </h2>

            <%= link_to("清空购物车", clean_carts_path,
              method: :delete , class: "pull-right",
              style: "text-decoration: underline;",
              data: { confirm: "你确定要清空整个购物车吗？"} )%>
            <br>

                  <table class="table table-boldered" ><thead>
                    <thead>
                      <tr>
                        <th colspan="2">商品资讯</th>
                        <th>单价</th>
                        <th>数量</th>
                        <th>操作选项</th>
                      </tr>
                    </thead>
                    <tbody>

                      <% current_cart.cart_items.each do |cart_item| %>
                        <tr>
                          <td width="15%">
                            <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
                          </td>
                         <td width="40%">
                            <%= link_to product_path(cart_item.product) do %>
                              <% if cart_item.product.image.present? %>
                                <%= image_tag(cart_item.product.image.thumb.url, class: "thumbnail") %>
                              <% else %>
                                <%= image_tag(cart_item.product.image_path, class: "thumbnail") %>
                              <% end %>
                            <% end %>
                          </td>
                          <%if cart_item.product.id==2 || cart_item.product.id==4%>
                            <%if cart_item.product.fund_price1==0%>
                            <td width="15%">
                              ￥<%= cart_item.product.fund_price2%>
                            </td>
                            <%elsif cart_item.product.fund_price2==0%>
                            <td width="15%">
                              ￥<%= cart_item.product.fund_price1%>
                            </td>
                            <%end%>
                          <%else%>
                          <td width="15%">
                            ￥<%= cart_item.product.price %>
                          </td>
                          <%end%>

                          <td width="15%">
                            <!-- <%= cart_item.quantity %> -->
                            <% cart_item = current_cart.cart_items.find_by(product_id: cart_item.product_id) %>
                            <%= form_for cart_item, url: cart_item_path(cart_item.product_id) do |f| %>
                             <%= f.select :quantity, 1..cart_item.product.quantity %>
                             <%= f.submit " 更新 ", data: { disable_with: "Submiting..." } %>
                            <% end %>
                          </td>
                          <td width="15%">
                           <%= link_to cart_item_path(cart_item.product_id), method: :delete do %>
                             <i class="fa fa-trash"></i>
                           <% end %>
                         </td>
                        </tr>
                      <% end %>

                    </tbody>
                  </table>
                  <br>

                        <div id="contCartTotalAmount">
                            <DIV id=orderSums class=clearfix>
                                <div class="totalSum">
                                    总计金额
                                    <span class=price>
                                        <SPAN class=num>
                                            ￥<%= render_cart_total_price(current_cart) %>
                                        </SPAN>
                                    </span>
                                </DIV>

                            </div>
                            <!--/#tblCartTotalAmount-->

                            <!-- stat FSC-03-010_5_de // -->
                            <!-- start FSC-03-010_5 // -->
                            <div id="agb_mobile">
                            <li onclick="obj=document.getElementById('id1').style; obj.display=(obj.display=='none')?'block':'none';">
                                <a>购物指南</a><br><br>
                                <ul id="id1" style="display: none;">
                                    <p> 单笔订单消费购买小件商品满500.00元。<br>
                                        可享受免费顺风快递。<br>
                                    </p>
                                </DIV>

                                <DIV id=agb>
                                      单笔订单消费购买小件商品满500.00元。<br>
                                      可享受免费顺风快递。<br>
                                </DIV>
                                <!-- // end FSC-03-010_5 -->

                                <!-- end FSC-03-010_5_de // -->

                                <div id="submitButton" class="panel button displaced">
                                    <%= link_to("确认结账", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right") %>
                                </div>



                            </div>

                    </div>
                </div>
              </div>
            </body>
        </html>