config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    sessions:'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :products
    resources :orders do
        member do
          post :cancel
          post :ship
          post :shipped
          post :return
        end
      end
  end

  namespace :account do
    resources :orders
  end


  resources :products do
    member do
      get :funding_product
      post :add_to_cart
      post :add_to_cart_f
    end
    collection do
       get :search
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders  do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end


  # root 'welcome#index'
  root 'products#index'

  get '/health' => 'activity#health'
  get 'funding' => 'products#funding'
  # get 'funding_product' => 'products#funding_product'
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates_presence_of :friendly_id

  validates_uniqueness_of :friendly_id
  validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/

  # validates :image, presence: true

  def to_param
     self.friendly_id
   end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit]
  before_action :admin_required

 layout "admin"

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice]="create product successful"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def edit
    @product = Product.find_by_friendly_id!(params[:id])
  end

  def update
    @product = Product.find_by_friendly_id!(params[:id])

    if @product.update(product_params)
      flash[:notice]="update successful"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def show
    @product = Product.find_by_friendly_id!(params[:id])
  end

  def destroy
    @product = Product.find_by_friendly_id!(params[:id])

    @product.destroy

    redirect_to admin_products_path
  end


  private

  def product_params
    # params.require(:product).permit(:title, :description, :quantity, :price)
    params.require(:product).permit(:title, :description, :quantity, :price, :image, :categories, :image_path, :is_discounted, :original_price, :is_fund, :fund_price1, :fund_price2, :friendly_id)

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
     @products = Product.all
  end

  def show
    # @product = Product.find_by_friendly_id!(params[:id])
    @product = Product.find_by_friendly_id!(params[:id])
  end

  def add_to_cart
    @product = Product.find_by_friendly_id!(params[:id])
    if !current_cart.products.include?(@product)
      if @product.id==2 || @product.id==4
        @product.fund_price1=1
        @product.fund_price2=0
        @product.save
      end
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功将 #{@product.title}加入购物车"
    else
      flash[:warning]="你的购物车内已有此物品"
    end
    redirect_to :back
  end

  def add_to_cart_f
    @product = Product.find_by_friendly_id!(params[:id])
    if !current_cart.products.include?(@product)
      if @product.id==2  #小米口罩
        @product.fund_price2=49
        @product.fund_price1=0
        @product.save
      elsif @product.id==4  #空气果
        @product.fund_price2=799
        @product.fund_price1=0
        @product.save
      end
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功将 #{@product.title}加入购物车"
    else
      flash[:warning]="你的购物车内已有此物品"
    end
    redirect_to :back
  end

  def search
    @query = @query_string
     if @query_string.present?
     if 0 == @query_string.casecmp("discounted")
       search_result = Product.where(is_discounted: true)
     else
     # search_result = Product.ransack(@search_criteria).result(distinct: true)
     # params.require(:product).permit(:title, :description, :quantity, :price, :image, :categories, :image_path, )
     search_result = Product.ransack({:title_or_categories_cont => @query_string}).result(distinct: true)
     # search_result = Product.ransack({{:title_or_field_or_location_or_company_name_cont => @q}}).result(distinct: true)
     end
     @products = search_result
     else
    # @jobs = Job.published.recent.paginate(page: params[:page], per_page:5)
     @products = Product.order('created_at DESC')
     end
   end

  def funding_product

      @product = Product.find_by_friendly_id!(params[:id])

  end






   protected
      def validate_search_key
        @query_string = params[:query_string].gsub(/\\|\'|\/|\?/, '') if params[:query_string].present?
      end

      def search_criteria(query_string)
        { title_or_description_or_answers_content_cont: query_string }
      end

end

app/views/admin/products/edit.html.erb
<body id="labtop">
<div class="container-fluid">
  <%= render "common/navbar" %>
      <%= render "common/flashes" %>
<h2> Edit Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

 <div class="group">
   <%= f.input :friendly_id %>
   <p class="help-block">限小写英数字及横线，将作为网址的一部分</p>
 </div>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <div class="group">
    <%= f.input :categories %>
  </div>

  <% if @product.image.present? %>
   <span>目前商品图</span> <br>
   <%= image_tag(@product.image.thumb.url) %>
 <% end %>

  <div class="group">
   <%= f.input :image, as: :file %>
 </div>
  <div class="group">
    <strong>Is_Fund: </strong><%=f.select :is_fund, [true,false]%>
  </div>

 <% if @product.image_url.present? %>
  <span>目前商品链接</span> <br>
  <%= f.input :image_url %>
<% end %>


  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>
</div>
</body>

app/views/admin/products/index.html.erb
<body id="labtop">
<div class="container-fluid">
  <%= render "common/navbar" %>
      <%= render "common/flashes" %>
<h2> Product List </h2>

<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th width="100"> Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.image.present? %>
              <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag(product.image_path, class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= product.created_at.strftime("%Y/%m/%d %I:%M %p") %>
        </td>
        <td>
          <%= link_to("Edit", edit_admin_product_path(product)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</body>

app/views/admin/products/new.html.erb
<body id="labtop">
<div class="container-fluid">
  <%= render "common/navbar" %>
      <%= render "common/flashes" %>
<h2> New Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

<div class="group">
  <%= f.input :friendly_id %>
  <p class="help-block">限小写英数字及横线，将作为网址的一部分</p>
</div>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <div class="group">
    <%= f.input :categories %>
  </div>

  <div class="group">
    <%= f.input :image, as: :file %>
 </div>

  <div class="group">
  <%= f.input :image_path %>
 </div>
 <div class="group">
   <strong>Is_Fund: </strong><%=f.select :is_fund, [true,false]%>
 </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>
</div>
</body>

app/views/admin/products/show.html.erb
<body>
<div class="container-fluid">
  <%= render "common/navbar" %>
      <%= render "common/flashes" %>
<h1> <%= @product.title %> </h1>

<p>
  <%= simple_format(@product.description) %>
  <%= @product.quantity %>
  <%= @product.price %>
  <%= @product.categories %>

</p>
</div>
</body>