config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    sessions:'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :products
    resources :orders do
        member do
          post :cancel
          post :ship
          post :shipped
          post :return
        end
      end
  end

  namespace :account do
    resources :orders
  end


  resources :products do
    member do
      get :funding_product
      post :add_to_cart
      post :add_to_cart_f
    end
    collection do
       get :search
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders  do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end


  # root 'welcome#index'
  root 'products#index'

  get '/health' => 'activity#health'
  get 'funding' => 'products#funding'
  # get 'funding_product' => 'products#funding_product'
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates_presence_of :friendly_id

  validates_uniqueness_of :friendly_id
  validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/

  # validates :image, presence: true

  def to_param
     self.friendly_id
   end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit]
  before_action :admin_required

 layout "admin"

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice]="create product successful"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def edit
    @product = Product.find_by_friendly_id!(params[:id])
  end

  def update
    @product = Product.find_by_friendly_id!(params[:id])

    if @product.update(product_params)
      flash[:notice]="update successful"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def show
    @product = Product.find_by_friendly_id!(params[:id])
  end

  def destroy
    @product = Product.find_by_friendly_id!(params[:id])

    @product.destroy

    redirect_to admin_products_path
  end


  private

  def product_params
    # params.require(:product).permit(:title, :description, :quantity, :price)
    params.require(:product).permit(:title, :description, :quantity, :price, :image, :categories, :image_path, :is_discounted, :original_price, :is_fund, :fund_price1, :fund_price2, :friendly_id)

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
     @products = Product.all
  end

  def show
    # @product = Product.find_by_friendly_id!(params[:id])
    @product = Product.find_by_friendly_id!(params[:id])
  end

  def add_to_cart
    @product = Product.find_by_friendly_id!(params[:id])
    if !current_cart.products.include?(@product)
      if @product.id==2 || @product.id==4
        @product.fund_price1=1
        @product.fund_price2=0
        @product.save
      end
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功将 #{@product.title}加入购物车"
    else
      flash[:warning]="你的购物车内已有此物品"
    end
    redirect_to :back
  end

  def add_to_cart_f
    @product = Product.find_by_friendly_id!(params[:id])
    if !current_cart.products.include?(@product)
      if @product.id==2  #小米口罩
        @product.fund_price2=49
        @product.fund_price1=0
        @product.save
      elsif @product.id==4  #空气果
        @product.fund_price2=799
        @product.fund_price1=0
        @product.save
      end
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功将 #{@product.title}加入购物车"
    else
      flash[:warning]="你的购物车内已有此物品"
    end
    redirect_to :back
  end

  def search
    @query = @query_string
     if @query_string.present?
     if 0 == @query_string.casecmp("discounted")
       search_result = Product.where(is_discounted: true)
     else
     # search_result = Product.ransack(@search_criteria).result(distinct: true)
     # params.require(:product).permit(:title, :description, :quantity, :price, :image, :categories, :image_path, )
     search_result = Product.ransack({:title_or_categories_cont => @query_string}).result(distinct: true)
     # search_result = Product.ransack({{:title_or_field_or_location_or_company_name_cont => @q}}).result(distinct: true)
     end
     @products = search_result
     else
    # @jobs = Job.published.recent.paginate(page: params[:page], per_page:5)
     @products = Product.order('created_at DESC')
     end
   end

  def funding_product

      @product = Product.find_by_friendly_id!(params[:id])

  end






   protected
      def validate_search_key
        @query_string = params[:query_string].gsub(/\\|\'|\/|\?/, '') if params[:query_string].present?
      end

      def search_criteria(query_string)
        { title_or_description_or_answers_content_cont: query_string }
      end

end

app/views/products/funding.html.erb
<style>
.header-bg-color {
    background-color: #ECEFF4;
}
/*.competition {
    max-width: 1240px;
}*/
.center-block {
    display: block;
    margin-left: auto;
    margin-right: auto;
}
.block1 {
    height: auto;
    background-color: #ECEFF4;
}
.header-bg {
    /*background-image: url(/app/public/images/funding.png);*/
    background-size: 100%;
}
/*.season-2 .btn-area-seson2 {
    width: 100%;
    height: 100%;
    max-height: 80px;
    position: relative;
    z-index: 41;
    font-size: 14px;
}
.season-2 .btn-area-seson2 .big-btn {
    width: 100%;
    height: 100%;
    top: -35px;
    position: relative;
    z-index: 42;
}*/
.btn, .btn:hover{
  /*margin-left:-90px;*/
   width:250px;
   border-radius: 1px;
   background-color: rgba(195,27,29,0.9);
   border: 1px solid rgba(195,27,29,0.9);
   box-shadow: 0 2px 4px 0 rgba(0,0,0,0.5);
   letter-spacing: 3px;
   margin-top:-20px;
   margin-left:-20%;
  /*margin-bottom:-10px;*/
   position:absolute;
}
.btn:active{
  background-color:rgba(195,27,29,0.9);

}
.btn-primary:active{
  background-color:rgba(195,27,29,0.9);
}
</style>

<%= render "common/navbar" %>
		<%= render "common/flashes" %>

<div class="header-bg-color">
    <div class="competition center-block block1">
      <div class="header-bg">
        <img src="/images/funding.png"style="width:100%;"/>
      </div>
    </div>
</div>

<div class="container-fluid text-center bg-grey">

    <div class="row text-center" >
      <div class="col-sm-6">
        <%@product=Product.find(4)%>
        <%= link_to("支持空气果", funding_product_product_path(@product), class: "btn btn-primary btn-lg")  %>
        <div class="thumbnail" >
          <img src="/images/funding_kqg.jpg" alt="空气果" />
          <p style="margin-top:10px;font-size:20px"><strong>空气果1S智能空气检测仪</strong></p>
          <p>随时掌握空气 | 免受污染侵害 | 和空气极客做朋友</p>
        </div>
      </div>
      <div class="col-sm-6">
        <%@product=Product.find(2)%>
        <%= link_to("支持小米口罩", funding_product_product_path(@product), class: "btn btn-primary btn-lg")  %>
        <div class="thumbnail" >
          <img src="/images/funding_kz.jpg" alt="小米口罩">
          <p style="margin-top:10px;font-size:20px"><strong>小米防雾霾口罩</strong></p>
          <p>贴合性密闭 | 柔性立体结构 | 舒适穿戴</p>
        </div>
      </div>
  </div>
</div>

app/views/products/funding_product.html.erb
<head>
	<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script> -->

	<style>
	ul > li{margin-right:30px;font-size:14px;cursor:pointer}
	li.active{border-bottom:3px solid silver;}
	.item-photo{display:flex;justify-content:center;align-items:center;border-right:1px solid #f6f6f6;}
	.menu-items{list-style-type:none;font-size:11px;display:inline-flex;margin-bottom:0px;margin-top:20px}
	.section{width:100%;margin-left:-15px;padding:2px;padding-left:15px;padding-right:15px;background:#f8f9f9}
	.btn-minus{cursor:pointer;font-size:7px;display:flex;align-items:center;padding:5px;padding-left:10px;padding-right:10px;border:1px solid gray;border-radius:2px;border-right:0px;}
	.btn-plus{cursor:pointer;font-size:7px;display:flex;align-items:center;padding:5px;padding-left:10px;padding-right:10px;border:1px solid gray;border-radius:2px;border-left:0px;}
	div.section > div {width:100%;display:inline-flex;}
	div.section > div > input {margin:0px;padding-left:5px;font-size:10px;padding-right:5px;max-width:18%;text-align:center;}



	</style>
</head>

<body>
	<div class="container-fluid">
	<%= render "common/navbar" %>
			<%= render "common/flashes" %>

<div class="container">
	<div class="row">
   <div class="col-xs-6 item-photo" id="div1">


		<!-- <img src="/images/funding_kqg.jpg	" alt="空气果"/> -->
  </div>
  <div class="col-xs-6" style="border:0px solid gray">

    <h3 id="tt"><%= @product.title %></h3>
			<p>
				已筹到
			</p>
			<p id="pp" style="font-size:30px;margin-top:5px;">
				¥8999
			</p>
			<div class="p-line">

			</div>
			<p>
				此项目必须在 <span style="color:red;">2017年03月31日 </span>前得到 <span style="color:red;">￥100’000 </span>的支持才可成功！
			</p>
      </div>


    </div>


	</div>
</div>
<!-- 选项卡区 -->
<div class="row">
	<div class="col-sm-8" >
		<div class="productDecription">
		  <div class="productDecription-menuList">
		    <div class="productDecription-menuList-item current-now">功能</div>
		    <div class="productDecription-menuList-item">细节</div>
				<div class="productDecription-menuList-item">Why Me</div>

		  </div>
		  <div class="productDecription-content">
		    <div class="productDecription-content-item" style="display: block;">
						<center id="pf">
							<!-- js动态添加img标签 -->
						</center>
				</div>
		    <div class="productDecription-content-item">
					<center id="pd">
						<!-- js动态添加img标签 -->
					</center>

				</div>
				<div class="productDecription-content-item ">
					<p style="margin:50px;font-size:18px;height:1000px;">
						<%=@product.description%>
					</p>
				</div>
		  </div>
		</div>
	</div>
	<!-- 众筹区 -->
	<div class="col-sm-4 ">
	  <!-- 发起人 -->
	  <div class="funding-offer-item">
       <div class="funding-offer-item-title">
				项目发起人
			 </div>
			 <div class="text-center">
				 <div style="width:100%;"><img src="/images/air-logo.png" style="padding:5px 190px;"/></div>
				 <div class="thumbnail text-center" style="margin:0px 10px 20px 10px;width:38%;display:inline-block">
            <img src="/images/elz.jpg" />
						<p style="margin-top:5px;font-size:10px;">ElizaChen</p>
				 </div>
				 <div class="thumbnail text-center" style="margin:10px;width:38%;display:inline-block">
					 <img src="/images/coco.jpg" />
					 <p style="margin-top:5px;font-size:10px">Cococardry</p>
				 </div>
			 </div>

		</div>
		<!-- ¥1众筹抽奖 -->
		<div class="funding-offer-item">
			<div class="funding-offer-item-title">
		   ￥1
			</div>
			<div style="margin:20px;">
				<strong>无限额 </strong> | <span class="app-tag">抽奖档</span>
				<p style="margin-top:20px;">
					每满100位支持者抽取1位幸运用户。幸运用户将会获得<%= @product.title %>1台。届时防霾库将第一时间通知中奖者。
				</p>
				<span style="margin-top:10px;">
					配送费用： <strong>免运费</strong>
				</span><br/>

				<span style="margin-top:10px;">
					预计回报发送时间：<strong>项目众筹成功后30天内</strong>
				</span>
			</div>


    <div class="text-center">
			<%= link_to("支持¥1", add_to_cart_product_path(@product), :method => :post, :class => "btn btn-primary btn-danger mybtn") %>
		</div>
		</div>

		<!-- 优惠众筹 -->
		<div class="funding-offer-item">
			<div class="funding-offer-item-title" id="fp">
			 <!-- ￥799 -->
			</div>
			<div style="margin:20px;">
				<strong>无限额 </strong> | <span class="app-tag">优惠档</span>
				<p style="margin-top:20px;">
					感谢您对防霾库的支持，您将获得远低于市场价的<%= @product.title %>1台。
				</p>
				<span style="margin-top:10px;">
					配送费用： <strong>免运费</strong>
				</span><br/>

				<span style="margin-top:10px;">
					预计回报发送时间：<strong>项目众筹成功后30天内</strong>
				</span>
			</div>


    <div class="text-center">
			<%if @product.id==2%>
			  <a id="btn-fp"class="btn btn-primary btn-danger mybtn" rel="nofollow" data-method="post" href="/products/2/add_to_cart_f">
			  </a>
			<%else%>
			  <a id="btn-fp"class="btn btn-primary btn-danger mybtn" rel="nofollow" data-method="post" href="/products/4/add_to_cart_f">
			  </a>
			<%end%>
		</div>
		</div>
	</div>
</div>
</div>




</body>
<style>
 .app-tag {
    padding: 0 7px;
    height: 18px;
    color: #fff;
    background: #ffaa05;
    -moz-border-radius: 10px;
    -webkit-border-radius: 10px;
    border-radius: 10px;
}
.mybtn{
  /*margin-left:-90px;*/
	margin-top:10px;
	height:40px;
   width:150px;
   /*border-radius: 1px;*/
   letter-spacing: 2px;
   font-size:18px;
}

/*商品详情*/
.productDecription {
	border: 1px solid #f2f2f2;
	box-shadow: 0 0 40px rgba(216,216,216,.5);
	/*width: 810px;*/

}

.productDecription-menuList {
	margin: 0 20px;
	height: 60px;
  border-bottom: 1px solid #e6e6e6;
}

.productDecription-menuList-item {
	width: 192px;
	height: 56px;
	float: left;
	line-height: 56px;
	text-align: center;
	color: #323232;
	font-size: 18px;
	letter-spacing: 3px;
	cursor: pointer;
}

.productDecription-content {
	width: auto;
	height: auto;
	/*margin: 50px auto;*/
}

	.productDecription-content-item {
		display: none;
		width: auto;

	}


.funding-offer{
	width:300px;
	height:1000px;
  /*display: inline-block;*/
	margin-top: -100px;
	border: 1px solid #f2f2f2;
	box-shadow: 0 0 40px rgba(216,216,216,.5);
}
.funding-offer-item{
	/*width:inherit;*/
	border: 1px solid #f2f2f2;
	box-shadow: 0 0 40px rgba(216,216,216,.5);
	height:333px;
  margin-bottom:25px;
}
.funding-offer-item-title{
	text-align: center;
	line-height: 56px;
	height: 60px;
	font-size: 20px;
  border-bottom: 1px solid #e6e6e6;
}

.funding-product-description{
	border: 1px solid #f2f2f2;
	box-shadow: 0 0 40px rgba(216,216,216,.5);
	width: 810px;
  display: inline-block;
	/*float: left;*/
}

.current-now {
    color: #2fd6a2;
    font-weight: 700;
		border-bottom:4px solid #2fd6a2;
		/*padding: 0px;*/
}
.p-line{
	color: #2fd6a2;
}


</style>
<script>
// 切换选项卡
$(document).on('click', '.productDecription-menuList-item', function () {
  var index = $(this).index() //拿到这个「选项卡」的index，第一个是0，第二个是1，以此类推
  $('.productDecription-content-item').hide();
	$('.productDecription-content-item').eq(index).show();
	$('.productDecription-menuList-item').removeClass('current-now');
	$(this).addClass('current-now');
})
// 动态加载图片、信息
$(document).ready(function(){

	var imgtag=document.createElement('img');
	var div1=document.getElementById('div1');
	div1.appendChild(imgtag);
  // 功能
	var pf=document.getElementById('pf');
	var imgtag_function = new Array("imgtag_function1","imgtag_function2","imgtag_function3","imgtag_function4");
	for(var i=0;i<4	;i++){
		imgtag_function[i]=document.createElement('img');
	}

  // 细节
	var pd=document.getElementById('pd');
	var imgtag_detail = new Array("imgtag_detail1","imgtag_detail2","imgtag_detail3","imgtag_detail4");
	for(var j=0;j<4;j++){
		imgtag_detail[j]=document.createElement('img');
	}

  var tt=$('#tt').text();
  if(tt=="空气果"){
		document.getElementById('fp').innerHTML='¥799';
		document.getElementById('btn-fp').innerHTML='¥799';
		imgtag.setAttribute('src','/images/funding_kqg.jpg');
		imgtag.setAttribute('alt','空气果');
		pf.appendChild(imgtag_function[0]);
		pd.appendChild(imgtag_detail[0]);
		imgtag_function[0].setAttribute('src','/images/kqg_function.jpg');
		imgtag_detail[0].setAttribute('src','/images/kqg_detail.jpg');
	}else if (tt=="小米口罩") {
		imgtag.setAttribute('src','/images/funding_kz.jpg');
		imgtag.setAttribute('alt','口罩');
		// var pp=$('#pp').text();
		document.getElementById('pp').innerHTML='¥6888';
		document.getElementById('fp').innerHTML='¥49';
		document.getElementById('btn-fp').innerHTML='¥49';
    for(var i=0;i<4;i++){
			pf.appendChild(imgtag_function[i]);
		}
		imgtag_function[0].setAttribute('src','/images/kz_function1.jpg');
    imgtag_function[1].setAttribute('src','/images/kz_function2.jpg');
		imgtag_function[2].setAttribute('src','/images/kz_function3.jpg');
		imgtag_function[3].setAttribute('src','/images/kz_function4.jpg');
		for(var j=0;j<3;j++){
			pd.appendChild(imgtag_detail[j]);
		}
		imgtag_detail[0].setAttribute('src','/images/kz_detail_1.jpg');
		imgtag_detail[1].setAttribute('src','/images/kz_detail_2.jpg');
		imgtag_detail[2].setAttribute('src','/images/kz_detail_3.jpg');
	}else{
		imgtag.setAttribute('src','/images/panel/funding.jpeg');
		imgtag.setAttribute('alt','众筹');
		imgtag_function.setAttribute('src','/images/panel/funding.jpeg');
		imgtag_function.setAttribute('alt','众筹');
	}


})




</script>

app/views/products/search.html.erb
<!DOCTYPE html>

<html lang="zh-cn" xml:lang="zh-cn" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta name="Description" content="">
        <meta charset="utf-8"/>
        <link rel="contents" href="/" title="Home">
        <script type="text/javascript" src="//www.muji.com.cn/cn/store/js/FSC02210.js" charset="utf-8"></script>
        <link href="//www.muji.com.cn/cn/store/css/muji.css" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="//www.muji.com.cn/cn/store/js/mj-productListView_search.js" charset="utf-8"></script>

        <title>

            商品搜寻 | 防霾库
        </title>
    </head>

    <body id="labtop" background="/images/bg.jpg">
  <div class="container-fluid">
    <%= render "common/navbar" %>
        <%= render "common/flashes" %>

      <div class="container-fluid" style="padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto;">
        <script type="text/javascript">
            function showBag(flg) {
                if (flg == "1") {
                    document.getElementById("gnav_cart_target").style.display = 'block';
                } else {
                    document.getElementById("gnav_cart_target").style.display = 'none';
                }

            }
        </script>

        <div class="content">
            <nav id="sideNav" style="float: left; width: 150px; margin-left: 50px; margin-right: 30px; margin-top: 113px;">
                <h2>进阶搜索</h2>
                <div id="snCategory">
                    <ul class="snCategoryL1">
                        <li>
                            <h3 class="contentClose">选择类别</h3>
                            <ul class="snCategoryL2">
                                <li>
                                    <%= link_to("防霾口罩", search_products_path(:order => "created_at", :query_string => "防霾口罩"), method: :get) %>
                                </li>
                                <li>
                                    <%= link_to("霾表", search_products_path(:order => "created_at", :query_string => "霾表"), method: :get) %>
                                </li>
                                <li>
                                    <%= link_to("空气净化", search_products_path(:order => "created_at", :query_string => "空气净化器"), method: :get) %>
                                </li>
                                <li>
                                    <%= link_to("所有商品", search_products_path(:order => "created_at", :query_string => ""), method: :get) %>
                                </li>
                            </ul>
                        </li>
                        <!-- <li><h3 class="contentClose">选择价格</h3>
   				<ul class="snCategoryL2">
   					<li>
								<a href="FSC02210E01.do?qtext=%E7%81%AF&amp;qstart=0&amp;sort=goods_disp_priority&amp;qrow=50&qrange=49%E5%85%83%E4%BB%A5%E4%B8%8B">
									99元以下
								</a>
							</li>
		         <li>
								<a href="FSC02210E01.do?qtext=%E7%81%AF&amp;qstart=0&amp;sort=goods_disp_priority&amp;qrow=50&qrange=50%E5%85%83%EF%BD%9E99%E5%85%83">
									99元～999元
								</a>
							</li>
							<li>
								<a href="FSC02210E01.do?qtext=%E7%81%AF&amp;qstart=0&amp;sort=goods_disp_priority&amp;qrow=50&qrange=100%E5%85%83%EF%BD%9E199%E5%85%83">
									1000元～9999元
								</a>
							</li>
					</ul>
				</li> TBD  later do it-->
                    </ul>
                    <ul class="snCategoryL1">
                        <li class="D00010">
                            <h3 id="features">精选・新到商品</h3>
                            <ul class="snCategoryL2">
                                <li>
                                <%= link_to("优惠活动", search_products_path(:order => "created_at", :query_string => "discounted"), method: :get)%>
                                </li>
                                <li><%= link_to("防霾众筹", funding_path, method: :get) %></li>
                                <li><%= link_to("新到商品", search_products_path(:order => "created_at", :query_string => ""), method: :get) %></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <!-- start FSC-02-210-1 // -->
            <script>
                $("head").append('<meta content="width=device-width, initial-scale=1.0, user-scalable=yes" name="viewport">');
                $("body").attr("id", "search");
            </script>
            <link href="/cn/store/css/muji_cn.css" rel="stylesheet" type="text/css"/>
            <link href="/cn/store/css/store/store.css" rel="stylesheet" type="text/css"/>
            <link href="/cn/store/css/store/store_cn.css" rel="stylesheet" type="text/css"/>
            <link href="/cn/store/css/mobile.css" rel="stylesheet" type="text/css" media="only screen and (min-device-width : 320px) and (max-device-width : 767px)"/>
            <link href="/cn/store/css/mobile_cn.css" rel="stylesheet" type="text/css" media="only screen and (min-device-width : 320px) and (max-device-width : 767px)"/>
            <!-- //end FSC-02-210-1 -->

            <div id="main" style="min-height: 440px; padding:20px,60px,30px,60px;">
                <div class="productlistPager">
                    <div class="totalItems">
                        <span class="itemnum">9
                        </span>商品中
                        <span class="itemnum">
                            1-9
                        </span>商品
                    </div>
                </div>

                <section id="newItem">
                    <div class="wrap">
                        <ul>
                            <% if  @products.present? %>
                            <% @products.order('created_at DESC').each do |product| %>
                            <li style="width: 22%">
                                  <dl class="info">
                                      <%= link_to product_path(product) do %>
                                      <% if product.image.present? %>
                                      <dt class="thumb">
                                          <%= image_tag(product.image.thumb.url)%>
                                      </dt>
                                  <% else %>
                                      <dt class="thumb">
                                          <%= image_tag(product.image_path, class: "thumb") %>
                                      </dt>
                                      <% end %>
                                      <br>
                                      <dd class="name"><%=product.title%></dd>
                                      <% end %>
                                      <%= link_to product_path(product) do %>
                                      <% if product.is_discounted %>
                                      <dd class="tag">
                                        <dd class="tag">
                                            <div class="tag sale" style="font-size: 11px; color:#7f0019; text-align:center;">限时特价商品</div>
                                        </dd>
                                      </dd>
                                      <dd class="price">
                                          <del>
                                              <span class="num">￥<%=product.original_price%></span>
                                          </del>
                                          <ins>
                                              <span class="num">￥<%=product.price%></span>
                                          </ins>
                                      </dd>
                                      <%elsif product.is_fund%>
                                      <dd class="price">
                                          <span>预估市场价</span>
                                          <ins>
                                              <span  style="color:#2fd6a2;" class="num">￥<%=product.price%></span>
                                          </ins>
                                      </dd>
                                      <% else %>
                                      <% if product.is_fund %>
                                      <span class="num">预估市场价</span>
                                      <dd class="price">
                                          <ins>
                                              <span class="num" style="color:#2fd6a2">￥<%=product.price%></span>
                                          </ins>
                                      </dd>
                                      <% else %>
                                      <dd class="price">
                                          <ins>
                                              <span class="num">￥<%=product.price%></span>
                                          </ins>
                                      </dd>

                                      <% end %>
                                      <% end %>
                                      <% end %>
                                  </dl>
                              </li>
                            <% end %>
                            <% end %>
                        </ul>
                    </div>

                </section>
            </div>
          </div>
        </div>
  </div>
</body>



    </html>