config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    sessions:'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :products
    resources :orders do
        member do
          post :cancel
          post :ship
          post :shipped
          post :return
        end
      end
  end

  namespace :account do
    resources :orders
  end


  resources :products do
    member do
      get :funding_product
      post :add_to_cart
      post :add_to_cart_f
    end
    collection do
       get :search
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders  do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end


  # root 'welcome#index'
  root 'products#index'

  get '/health' => 'activity#health'
  get 'funding' => 'products#funding'
  # get 'funding_product' => 'products#funding_product'
end

app/views/common/_footer.html.erb
<footer class="indoor-page" style="height: 168px;">
    <a href="/" target="_blank">
        <img src="/images/air-logo.png" style="margin-top:-5px; width:70px; height:25px;" alt="空气果"/>
    </a>

    <p>Copyright &copy;&nbsp; Design by elizachen & cococardry</p>
    <p>© 防霾库（上海）商业有限公司 地址：上海市静安区灵石路695号3号楼1楼</p>
    <p>沪ICP备08018XXX号&nbsp;&nbsp;</p>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            },
            i[r].l = 1 * new Date();
            a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    </script>
</footer>

app/views/common/_navbar.html.erb
<header id="globalHeader" style=" height:60px; padding:0px;">
    <!-- <h3 id="siteName">
          <a href="/" ><img src="/images/favicon-leaf.ico" style="margin-left:20px;margin-bottom:0px;width:30px;"/> 防霾库</a>
  </h3> -->
  <nav class="navbar navbar-default navbar-fixed-top" style="padding:0; height=70px;">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <!-- <a class="navbar-brand" href="#lp-pom-body">防霾库</a> -->
              <a href="/" class="navbar-brand">
                  <img src="/images/air-logo.png" style="margin-top:-5px; width:70px;" alt="防霾库"/>
              </a>
          </div>

          <div class="collapse navbar-collapse " id="myNavbar" style="70px">
              <ul class="nav navbar-nav">
                <li>
                    <%= link_to(t("product_list"), search_products_path(:order => "created_at", :query_string => ""), method: :get) %>
                </li>
                <li>
                   <%= link_to t("active"), :anchor => "event" %>
                    <!-- <a href="/#event">I18n.t("active")</a> -->
                </li>
                <li>
                  <%= link_to t("about"), :anchor => "about" %>
                   <!-- <a href="/#about">t("about")</a> -->
                </li>
                <li><%= link_to carts_path do  %>
                    <i class="fa fa-shopping-cart"></i>
                    (
                    <%= current_cart.products.count %>
                    )
                    <% end %>
                </li>
                <li>
                     <% if I18n.locale == I18n.default_locale %>
                     <%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %>
                     <% else %>
                     <%= link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-CN" %>
                     <% end %>
                </li>
                <li>
                    <% if !current_user %>
                    <li><%= link_to(content_tag(:i,'注册',class: 'fa fa-user'), new_user_registration_path, method: :get)  %></li>
                    <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path, method: :get)  %></li>

            <% else %>

                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!,<%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-left">

                        <% if current_user.admin? %>
                        <li>
                            <%= link_to("Admin 选单", admin_products_path ) %>
                        </li>
                        <% end %>
                        <li>
                            <%= link_to("个人订单列表", account_orders_path ) %>
                        </li>
                        <!-- <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li> -->
                        <li>
                            <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %>
                        </li>
                    </ul>
                </li>
                <% end %>

          </ul>
      </div>

      <ul class="nav navbar-nav navbar-right">
          <li id="hSearch" style="margin-top:10px; ">
              <!-- <form action="/cn/store/FSC02210E01.do?qcategory=all&qicon=&qstart=0&sort=goods_disp_priority&fid=header_search&qtext="
                  id="headerSearch" method="get"> -->
              <%= form_tag search_products_path, method: :get, class: 'questions-search-form'  do %>
              <h1>产品搜索</h1>
              <div class="wrapper">
                  <div class="cancel" style="text-align: left;">取消</div>
                  <!-- <input type="text" class="form-control" name="query_string" value="<%= params[:query_string] %>" placeholder="职位 种类 城市 区域..."> -->
                  <input type="search" placeholder="产品搜索" name="query_string" value="<%= params[:query_string] %>">
              </div>
              <!-- </form> -->
              <% end %>

          </li>
      </ul>

  </div>

</nav>

    <!-- .headerWrap -->
</header>